#!/usr/bin/env python3
import os

# Define the base physical address where Data RAM starts in your link_soc.ld
DATA_RAM_BASE = 0x2000

inst_lines = []
data_lines = []

# Default tracking target space
current_target = inst_lines

if not os.path.exists("full.mem"):
    print("Error: full.mem was not generated by objcopy!")
    exit(1)

with open("full.mem", "r") as f:
    for line in f:
        cleaned = line.strip()
        
        # Check if this line is an address pointer directive (e.g., @00002000)
        if cleaned.startswith("@"):
            # Convert hex string (excluding the '@') into an integer address
            current_addr = int(cleaned[1:], 16)
            
            if current_addr >= DATA_RAM_BASE:
                # Dynamic Relocation: Shift address relative to the base of Data SRAM
                adjusted_addr = current_addr - DATA_RAM_BASE
                data_lines.append(f"@{adjusted_addr:08x}\n")
                current_target = data_lines
            else:
                # Instruction space address pointers stay exactly as they are
                inst_lines.append(line)
                current_target = inst_lines
        else:
            # Standard data hex rows get appended to whichever file is currently active
            current_target.append(line)

# Save out the hardware-ready instruction memory image
with open("inst.mem", "w") as f:
    f.writelines(inst_lines)

# Save out the hardware-ready data memory image (including your CIFAR-10 weights!)
with open("data.mem", "w") as f:
    f.writelines(data_lines)

print("==========================================")
print(" Memory Splitter Execution Complete")
print("==========================================")
print(f" -> inst.mem: {len(inst_lines)} rows written (ROM Space)")
print(f" -> data.mem: {len(data_lines)} rows written (RAM Neural Net Space)")
print("==========================================")